name: modred-dae-torch
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - cloudpickle
  - pandas>=1.2.0
  - numpy
  - numexpr
  - sympy
  - cycler
  - tqdm
  - joblib
  - brewer2mpl
  - matplotlib
  - scipy
  - dill>=0.3.9
  - psutil
  - dask
  - distributed
  - dask-jobqueue
  - ipykernel
  - tectonic
  - jupyter