name: modred-dae-torch
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - brewer2mpl
  - cycler
  - matplotlib
  - numpy
  - scipy
  - spyder
  - sympy
  - time
  - numexpr
  - joblib
  - pathos
  - pytorch
  - pytorch-cuda=12.4
